// Package api provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.4.1 DO NOT EDIT.
package api

import (
	"time"
)

// Defines values for GroupMemberType.
const (
	GroupMemberTypeOrg  GroupMemberType = "Org"
	GroupMemberTypeUser GroupMemberType = "User"
)

// Defines values for ImageStatus.
const (
	ImageStatusActive   ImageStatus = "active"
	ImageStatusInactive ImageStatus = "inactive"
)

// Defines values for OrgMemberType.
const (
	OrgMemberTypeOrg  OrgMemberType = "Org"
	OrgMemberTypeUser OrgMemberType = "User"
)

// Defines values for RepositoryListEntryRepositoryType.
const (
	RepositoryListEntryRepositoryTypeImage       RepositoryListEntryRepositoryType = "image"
	RepositoryListEntryRepositoryTypeLessThannil RepositoryListEntryRepositoryType = "<nil>"
	RepositoryListEntryRepositoryTypePlugin      RepositoryListEntryRepositoryType = "plugin"
)

// Defines values for RepositoryListEntryStatusDescription.
const (
	RepositoryListEntryStatusDescriptionActive   RepositoryListEntryStatusDescription = "active"
	RepositoryListEntryStatusDescriptionInactive RepositoryListEntryStatusDescription = "inactive"
)

// Defines values for TagStatus.
const (
	Active   TagStatus = "active"
	Inactive TagStatus = "inactive"
)

// Defines values for UserType.
const (
	UserTypeOrg  UserType = "Org"
	UserTypeUser UserType = "User"
)

// AuditLog Audit log event.
type AuditLog struct {
	Account           *string            `json:"account,omitempty"`
	Action            *string            `json:"action,omitempty"`
	ActionDescription *string            `json:"action_description,omitempty"`
	Actor             *string            `json:"actor,omitempty"`
	Data              *map[string]string `json:"data,omitempty"`
	Name              *string            `json:"name,omitempty"`
	Timestamp         *time.Time         `json:"timestamp,omitempty"`
}

// AuditLogAction Audit Log action
type AuditLogAction struct {
	// Description Description of audit log action.
	Description *string `json:"description,omitempty"`

	// Label Label for audit log action.
	Label *string `json:"label,omitempty"`

	// Name Name of audit log action.
	Name *string `json:"name,omitempty"`
}

// AuditLogActions defines model for AuditLogActions.
type AuditLogActions struct {
	// Actions List of audit log actions.
	Actions *[]AuditLogAction `json:"actions,omitempty"`

	// Label Grouping label for a particular set of audit log actions.
	Label *string `json:"label,omitempty"`
}

// GetAuditActionsResponse GetAuditActions response.
type GetAuditActionsResponse struct {
	// Actions Map of audit log actions.
	Actions *map[string]AuditLogActions `json:"actions,omitempty"`
}

// GetAuditLogsResponse GetAuditLogs response.
type GetAuditLogsResponse struct {
	// Logs List of audit log events.
	Logs *[]AuditLog `json:"logs,omitempty"`
}

// PostUsers2FALoginErrorResponse failed second factor login response.
type PostUsers2FALoginErrorResponse struct {
	// Detail Description of the error.
	Detail *string `json:"detail,omitempty"`
}

// PostUsersLoginErrorResponse failed user login response or second factor required
type PostUsersLoginErrorResponse struct {
	// Detail Description of the error.
	Detail string `json:"detail"`

	// Login2faToken Short time lived token to be used on `/v2/users/2fa-login` to complete the authentication. This field is present only if 2FA is enabled.
	Login2faToken *string `json:"login_2fa_token"`
}

// PostUsersLoginSuccessResponse successful user login response
type PostUsersLoginSuccessResponse struct {
	// RefreshToken Created refresh token.
	RefreshToken *string `json:"refresh_token,omitempty"`

	// Token Created authentication token.
	// This token can be used in the HTTP Authorization header as a JWT to authenticate with the Docker Hub APIs.
	Token *string `json:"token,omitempty"`
}

// Users2FALoginRequest Second factor user login details
type Users2FALoginRequest struct {
	// Code The Time-based One-Time Password of the Docker Hub account to authenticate with.
	Code string `json:"code"`

	// Login2faToken The intermediate 2FA token returned from `/v2/users/login` API.
	Login2faToken string `json:"login_2fa_token"`
}

// UsersLoginRequest User login details
type UsersLoginRequest struct {
	// Password The password or personal access token (PAT) of the Docker Hub account to authenticate with.
	Password string `json:"password"`

	// Username The username of the Docker Hub account to authenticate with.
	Username string `json:"username"`
}

// AccessToken defines model for accessToken.
type AccessToken struct {
	ClientId    *string    `json:"client_id,omitempty"`
	CreatedAt   *string    `json:"created_at,omitempty"`
	CreatorIp   *string    `json:"creator_ip,omitempty"`
	CreatorUa   *string    `json:"creator_ua,omitempty"`
	ExpiresAt   *time.Time `json:"expires_at,omitempty"`
	GeneratedBy *string    `json:"generated_by,omitempty"`
	IsActive    *bool      `json:"is_active,omitempty"`
	LastUsed    *string    `json:"last_used"`
	Scopes      *[]string  `json:"scopes,omitempty"`
	Token       *string    `json:"token,omitempty"`
	TokenLabel  *string    `json:"token_label,omitempty"`
	Uuid        *string    `json:"uuid,omitempty"`
}

// BulkInviteRequest defines model for bulk_invite.
type BulkInviteRequest struct {
	// Invitees A list of invitees
	Invitees *[]struct {
		Invite *Invite `json:"invite,omitempty"`

		// Invitee invitee email or Docker ID
		Invitee *string `json:"invitee,omitempty"`

		// Status status of the invite or validation error
		Status *string `json:"status,omitempty"`
	} `json:"invitees,omitempty"`
}

// Category Repository category for classification and discovery
type Category struct {
	// Name Human-readable name of the category
	Name string `json:"name"`

	// Slug URL-friendly identifier for the category
	Slug string `json:"slug"`
}

// CreateAccessTokenRequest defines model for createAccessTokenRequest.
type CreateAccessTokenRequest struct {
	// ExpiresAt Optional expiration date for the token.
	// If omitted, the token will remain valid indefinitely.
	ExpiresAt *time.Time `json:"expires_at,omitempty"`

	// Scopes Valid scopes: "repo:admin", "repo:write", "repo:read", "repo:public_read"
	Scopes []string `json:"scopes"`

	// TokenLabel Friendly name for you to identify the token.
	TokenLabel string `json:"token_label"`
}

// CreateAccessTokensResponse defines model for createAccessTokensResponse.
type CreateAccessTokensResponse = AccessToken

// GetAccessTokensResponse defines model for getAccessTokensResponse.
type GetAccessTokensResponse struct {
	ActiveCount *float32       `json:"active_count,omitempty"`
	Count       *float32       `json:"count,omitempty"`
	Next        *string        `json:"next,omitempty"`
	Previous    *string        `json:"previous,omitempty"`
	Results     *[]AccessToken `json:"results,omitempty"`
}

// GroupMember defines model for group_member.
type GroupMember struct {
	Company       *string    `json:"company,omitempty"`
	DateJoined    *time.Time `json:"date_joined,omitempty"`
	Email         *string    `json:"email,omitempty"`
	FullName      *string    `json:"full_name,omitempty"`
	GravatarEmail *string    `json:"gravatar_email,omitempty"`
	GravatarUrl   *string    `json:"gravatar_url,omitempty"`

	// Id The UUID trimmed
	Id         *string          `json:"id,omitempty"`
	Location   *string          `json:"location,omitempty"`
	ProfileUrl *string          `json:"profile_url,omitempty"`
	Type       *GroupMemberType `json:"type,omitempty"`
	Username   *string          `json:"username,omitempty"`
}

// GroupMemberType defines model for GroupMember.Type.
type GroupMemberType string

// HubPlan defines model for hub_plan.
type HubPlan struct {
	Collaborators  *int    `json:"collaborators,omitempty"`
	Duration       *string `json:"duration,omitempty"`
	Legacy         *bool   `json:"legacy,omitempty"`
	Name           *string `json:"name,omitempty"`
	ParallelBuilds *int    `json:"parallel_builds,omitempty"`
	PrivateRepos   *int    `json:"private_repos,omitempty"`
	Seats          *int    `json:"seats,omitempty"`
	Teams          *int    `json:"teams,omitempty"`
}

// Image defines model for image.
type Image struct {
	// Architecture CPU architecture
	Architecture *string `json:"architecture,omitempty"`

	// Digest image digest
	Digest *string `json:"digest"`

	// Features CPU features
	Features *string `json:"features,omitempty"`

	// LastPulled datetime of last pull
	LastPulled *string `json:"last_pulled"`

	// LastPushed datetime of last push
	LastPushed *string  `json:"last_pushed"`
	Layers     *[]Layer `json:"layers,omitempty"`

	// Os operating system
	Os *string `json:"os,omitempty"`

	// OsFeatures OS features
	OsFeatures *string `json:"os_features,omitempty"`

	// OsVersion OS version
	OsVersion *string `json:"os_version,omitempty"`

	// Size size of the image
	Size *int `json:"size,omitempty"`

	// Status Status of the image
	Status *ImageStatus `json:"status,omitempty"`

	// Variant CPU variant
	Variant *string `json:"variant,omitempty"`
}

// ImageStatus Status of the image
type ImageStatus string

// ImmutableTagsSettings defines model for immutable_tags_settings.
type ImmutableTagsSettings struct {
	// Enabled Whether immutable tags are enabled
	Enabled bool `json:"enabled"`

	// Rules List of immutable tag rules
	Rules []string `json:"rules"`
}

// Invite defines model for invite.
type Invite struct {
	CreatedAt *string `json:"created_at,omitempty"`

	// Id uuid representing the invite id
	Id *string `json:"id,omitempty"`

	// Invitee can either be a dockerID for registered users or an email for non-registered users
	Invitee         *string `json:"invitee,omitempty"`
	InviterUsername *string `json:"inviter_username,omitempty"`

	// Org name of the org to join
	Org *string `json:"org,omitempty"`

	// Team name of the team (user group) to join
	Team *string `json:"team,omitempty"`
}

// Layer defines model for layer.
type Layer struct {
	// Digest image layer digest
	Digest *string `json:"digest"`

	// Instruction Dockerfile instruction
	Instruction *string `json:"instruction,omitempty"`

	// Size size of the layer
	Size *int `json:"size,omitempty"`
}

// ListRepositoriesResponse defines model for list_repositories_response.
type ListRepositoriesResponse struct {
	// Count total number of results available across all pages
	Count *int `json:"count,omitempty"`

	// Next link to next page of results if any
	Next *string `json:"next"`

	// Previous link to previous page of results  if any
	Previous *string                `json:"previous"`
	Results  *[]RepositoryListEntry `json:"results,omitempty"`
}

// OrgGroup defines model for org_group.
type OrgGroup struct {
	// Description Description of the group
	Description *string `json:"description,omitempty"`

	// Id Group ID
	Id *float32 `json:"id,omitempty"`

	// MemberCount Member count of the group
	MemberCount *float32 `json:"member_count,omitempty"`

	// Name Name of the group
	Name *string `json:"name,omitempty"`

	// Uuid UUID for the group
	Uuid *string `json:"uuid,omitempty"`
}

// OrgGroupPaginated defines model for org_group_paginated.
type OrgGroupPaginated struct {
	Count    *int        `json:"count,omitempty"`
	Next     *string     `json:"next"`
	Previous *string     `json:"previous"`
	Results  *[]OrgGroup `json:"results,omitempty"`
}

// OrgMember defines model for org_member.
type OrgMember struct {
	Company       *string    `json:"company,omitempty"`
	DateJoined    *time.Time `json:"date_joined,omitempty"`
	Email         *string    `json:"email,omitempty"`
	FullName      *string    `json:"full_name,omitempty"`
	GravatarEmail *string    `json:"gravatar_email,omitempty"`
	GravatarUrl   *string    `json:"gravatar_url,omitempty"`

	// Id The UUID trimmed
	Id         *string        `json:"id,omitempty"`
	Location   *string        `json:"location,omitempty"`
	ProfileUrl *string        `json:"profile_url,omitempty"`
	Type       *OrgMemberType `json:"type,omitempty"`
	Username   *string        `json:"username,omitempty"`
}

// OrgMemberType defines model for OrgMember.Type.
type OrgMemberType string

// OrgMemberPaginated defines model for org_member_paginated.
type OrgMemberPaginated struct {
	// Count The total number of items that match with the search.
	Count *float32 `json:"count,omitempty"`

	// Next The URL or link for the next page of items.
	Next *string `json:"next,omitempty"`

	// Previous The URL or link for the previous page of items.
	Previous *string `json:"previous,omitempty"`

	// Results List of accounts.
	Results *[]OrgMember `json:"results,omitempty"`
}

// PageInfo defines model for page.
type PageInfo struct {
	// Count total number of results available across all pages
	Count *int `json:"count,omitempty"`

	// Next link to next page of results if any
	Next *string `json:"next"`

	// Previous link to previous page of results  if any
	Previous *string `json:"previous"`
}

// PaginatedTags defines model for paginated_tags.
type PaginatedTags struct {
	// Count total number of results available across all pages
	Count *int `json:"count,omitempty"`

	// Next link to next page of results if any
	Next *string `json:"next"`

	// Previous link to previous page of results  if any
	Previous *string `json:"previous"`
	Results  *[]Tag  `json:"results,omitempty"`
}

// PatchAccessTokenRequest defines model for patchAccessTokenRequest.
type PatchAccessTokenRequest struct {
	IsActive   *bool   `json:"is_active,omitempty"`
	TokenLabel *string `json:"token_label,omitempty"`
}

// PatchAccessTokenResponse defines model for patchAccessTokenResponse.
type PatchAccessTokenResponse = AccessToken

// RepoPermissions defines model for repo_permissions.
type RepoPermissions struct {
	// Admin Admin permission
	Admin bool `json:"admin"`

	// Read Read permission
	Read bool `json:"read"`

	// Write Write permission
	Write bool `json:"write"`
}

// RepositoryInfo defines model for repository_info.
type RepositoryInfo struct {
	// Affiliation Repository affiliation
	Affiliation *string `json:"affiliation"`

	// Categories Repository categories
	Categories []Category `json:"categories"`

	// CollaboratorCount Number of collaborators
	CollaboratorCount int64 `json:"collaborator_count"`

	// ContentTypes Supported content types
	ContentTypes []string `json:"content_types"`

	// DateRegistered ISO 8601 timestamp of when repository was created
	DateRegistered time.Time `json:"date_registered"`

	// Description Short description of the repository
	Description string `json:"description"`

	// FullDescription Full description of the repository
	FullDescription *string `json:"full_description"`

	// HasStarred Whether the current user has starred this repository
	HasStarred bool `json:"has_starred"`

	// HubUser Hub user information
	HubUser               *string               `json:"hub_user"`
	ImmutableTagsSettings ImmutableTagsSettings `json:"immutable_tags_settings"`

	// IsAutomated Whether the repository has automated builds
	IsAutomated bool `json:"is_automated"`

	// IsPrivate Whether the repository is private
	IsPrivate bool `json:"is_private"`

	// LastModified ISO 8601 timestamp of when repository was last modified
	LastModified *time.Time `json:"last_modified"`

	// LastUpdated ISO 8601 timestamp of when repository was last updated
	LastUpdated time.Time `json:"last_updated"`

	// MediaTypes Supported media types
	MediaTypes []string `json:"media_types"`

	// Name Repository name
	Name string `json:"name"`

	// Namespace Repository namespace
	Namespace   string          `json:"namespace"`
	Permissions RepoPermissions `json:"permissions"`

	// PullCount Number of pulls
	PullCount int64 `json:"pull_count"`

	// RepositoryType Type of the repository
	RepositoryType *string `json:"repository_type"`

	// Source Source of the repository, where it was created from
	Source *string `json:"source"`

	// StarCount Number of stars
	StarCount int64 `json:"star_count"`

	// Status Repository status code
	Status int `json:"status"`

	// StatusDescription Description of the repository status
	StatusDescription string `json:"status_description"`

	// StorageSize Storage size in bytes
	StorageSize *int64 `json:"storage_size"`

	// User Username of the repository owner
	User string `json:"user"`
}

// RepositoryListEntry defines model for repository_list_entry.
type RepositoryListEntry struct {
	// Affiliation User's affiliation with the repository (empty string if no affiliation)
	Affiliation *string `json:"affiliation,omitempty"`

	// Categories Categories associated with this repository
	Categories *[]Category `json:"categories,omitempty"`

	// ContentTypes Content types supported by this repository
	ContentTypes *[]string `json:"content_types,omitempty"`

	// DateRegistered ISO 8601 timestamp of when the repository was created
	DateRegistered *time.Time `json:"date_registered,omitempty"`

	// Description Repository description
	Description *string `json:"description"`

	// IsPrivate Whether the repository is private
	IsPrivate *bool `json:"is_private,omitempty"`

	// LastModified ISO 8601 timestamp of when the repository was last modified
	LastModified *time.Time `json:"last_modified"`

	// LastUpdated ISO 8601 timestamp of when the repository was last updated
	LastUpdated *time.Time `json:"last_updated"`

	// MediaTypes Media types supported by this repository
	MediaTypes *[]string `json:"media_types,omitempty"`

	// Name Name of the repository
	Name *string `json:"name,omitempty"`

	// Namespace Namespace (organization or username) that owns the repository
	Namespace *string `json:"namespace,omitempty"`

	// PullCount Total number of pulls for this repository
	PullCount *int `json:"pull_count,omitempty"`

	// RepositoryType Type of repository
	RepositoryType *RepositoryListEntryRepositoryType `json:"repository_type"`

	// StarCount Number of users who starred this repository
	StarCount *int `json:"star_count,omitempty"`

	// Status Repository status code
	Status *int `json:"status,omitempty"`

	// StatusDescription Human-readable repository status
	StatusDescription *RepositoryListEntryStatusDescription `json:"status_description,omitempty"`

	// StorageSize Storage size in bytes used by this repository
	StorageSize *int `json:"storage_size,omitempty"`
}

// RepositoryListEntryRepositoryType Type of repository
type RepositoryListEntryRepositoryType string

// RepositoryListEntryStatusDescription Human-readable repository status
type RepositoryListEntryStatusDescription string

// Tag defines model for tag.
type Tag struct {
	// Creator ID of the user that pushed the tag
	Creator *int `json:"creator,omitempty"`

	// FullSize compressed size (sum of all layers) of the tagged image
	FullSize *int `json:"full_size,omitempty"`

	// Id tag ID
	Id     *int   `json:"id,omitempty"`
	Images *Image `json:"images,omitempty"`

	// LastUpdated datetime of last update
	LastUpdated *string `json:"last_updated"`

	// LastUpdater ID of the last user that updated the tag
	LastUpdater *int `json:"last_updater,omitempty"`

	// LastUpdaterUsername Hub username of the user that updated the tag
	LastUpdaterUsername *string `json:"last_updater_username,omitempty"`

	// Name name of the tag
	Name *string `json:"name,omitempty"`

	// Repository repository ID
	Repository *int `json:"repository,omitempty"`

	// Status whether a tag has been pushed to or pulled in the past month
	Status *TagStatus `json:"status,omitempty"`

	// TagLastPulled datetime of last pull
	TagLastPulled *string `json:"tag_last_pulled"`

	// TagLastPushed datetime of last push
	TagLastPushed *string `json:"tag_last_pushed"`

	// V2 repository API version
	V2 *string `json:"v2,omitempty"`
}

// TagStatus whether a tag has been pushed to or pulled in the past month
type TagStatus string

// User defines model for user.
type User struct {
	Company       *string `json:"company,omitempty"`
	DateJoined    *string `json:"date_joined,omitempty"`
	FullName      *string `json:"full_name,omitempty"`
	GravatarEmail *string `json:"gravatar_email,omitempty"`
	GravatarUrl   *string `json:"gravatar_url,omitempty"`

	// Id The UUID trimmed
	Id         *string   `json:"id,omitempty"`
	Location   *string   `json:"location,omitempty"`
	ProfileUrl *string   `json:"profile_url,omitempty"`
	Type       *UserType `json:"type,omitempty"`
	Username   *string   `json:"username,omitempty"`
}

// UserType defines model for User.Type.
type UserType string

// UserOrg defines model for user_org.
type UserOrg struct {
	Company       *string    `json:"company,omitempty"`
	DateJoined    *time.Time `json:"date_joined,omitempty"`
	FullName      *string    `json:"full_name,omitempty"`
	GravatarEmail *string    `json:"gravatar_email,omitempty"`
	GravatarUrl   *string    `json:"gravatar_url,omitempty"`
	Id            *string    `json:"id,omitempty"`
	Location      *string    `json:"location,omitempty"`
	Orgname       *string    `json:"orgname,omitempty"`
	ProfileUrl    *string    `json:"profile_url,omitempty"`
	Type          *string    `json:"type,omitempty"`
}

// UserOrgPaginated defines model for user_org_paginated.
type UserOrgPaginated struct {
	Count    *int       `json:"count,omitempty"`
	Next     *string    `json:"next"`
	Previous *string    `json:"previous"`
	Results  *[]UserOrg `json:"results,omitempty"`
}
