#!/bin/sh

set -eu

TMPDIR="$(mktemp -d)"
trap 'rm -rf "$TMPDIR"' EXIT
cp go.mod "$TMPDIR/go.mod"
cp go.sum "$TMPDIR/go.sum"

go mod tidy

if ! diff -u "$TMPDIR/go.mod" go.mod || ! diff -u "$TMPDIR/go.sum" go.sum; then
    echo
    echo "go.mod or go.sum is not tidy"
    exit 1
else
    echo "go.mod is correct"
fi
